// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkR9_m6EUpqEWH53NsbGi6QsDXylLsuwA',
    appId: '1:824505400698:web:32eec8ecbfcaafb953aac3',
    messagingSenderId: '824505400698',
    projectId: 'hamro-book-nepal',
    authDomain: 'hamro-book-nepal.firebaseapp.com',
    storageBucket: 'hamro-book-nepal.appspot.com',
    measurementId: 'G-8HGXWY7GGE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArL2kc4DfZsWvUoz1obl3y2ZZ9kcw_vIk',
    appId: '1:824505400698:android:90e24fc9f66a2c0b53aac3',
    messagingSenderId: '824505400698',
    projectId: 'hamro-book-nepal',
    storageBucket: 'hamro-book-nepal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1OhSMQX_ZMeP5--Jch6JYWR3_iIz5VfE',
    appId: '1:824505400698:ios:9bcf85eb53bc891153aac3',
    messagingSenderId: '824505400698',
    projectId: 'hamro-book-nepal',
    storageBucket: 'hamro-book-nepal.appspot.com',
    iosBundleId: 'com.example.eBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1OhSMQX_ZMeP5--Jch6JYWR3_iIz5VfE',
    appId: '1:824505400698:ios:e692dc3bd36755ee53aac3',
    messagingSenderId: '824505400698',
    projectId: 'hamro-book-nepal',
    storageBucket: 'hamro-book-nepal.appspot.com',
    iosBundleId: 'com.example.eBook.RunnerTests',
  );
}
